name: help_teacher
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^6.0.1
  get_it: ^7.2.0
  introduction_screen: ^3.1.4
  smooth_page_indicator: ^1.0.0+2
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5
  chips_choice: ^3.0.0
  dropdown_search: ^5.0.5
  fl_chart: ^0.60.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.1.1
  build_runner: ^2.3.3

flutter:

  uses-material-design: true
