// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABSey5z8ancvJ2D9bGGtG8VKEks5xRXfs',
    appId: '1:306962787599:web:6122ea77c697fd992fa27a',
    messagingSenderId: '306962787599',
    projectId: 'helpteacher-74184',
    authDomain: 'helpteacher-74184.firebaseapp.com',
    storageBucket: 'helpteacher-74184.appspot.com',
    measurementId: 'G-44F7YK0D2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlgfiCjspN9loZa2jIB-nQz8jY3UP8A98',
    appId: '1:306962787599:android:1501358d351531532fa27a',
    messagingSenderId: '306962787599',
    projectId: 'helpteacher-74184',
    storageBucket: 'helpteacher-74184.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFdkoD2mGhlVlYrpwbL4z7pSobmdEJe8A',
    appId: '1:306962787599:ios:abf96a6033eb91d02fa27a',
    messagingSenderId: '306962787599',
    projectId: 'helpteacher-74184',
    storageBucket: 'helpteacher-74184.appspot.com',
    iosClientId: '306962787599-kucqf1tmkidicpdd9ft4536k37tr7tv6.apps.googleusercontent.com',
    iosBundleId: 'com.example.helpTeacher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFdkoD2mGhlVlYrpwbL4z7pSobmdEJe8A',
    appId: '1:306962787599:ios:abf96a6033eb91d02fa27a',
    messagingSenderId: '306962787599',
    projectId: 'helpteacher-74184',
    storageBucket: 'helpteacher-74184.appspot.com',
    iosClientId: '306962787599-kucqf1tmkidicpdd9ft4536k37tr7tv6.apps.googleusercontent.com',
    iosBundleId: 'com.example.helpTeacher',
  );
}
